// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadColumns(arg1:string):Promise<Array<string>>;

export function SelectFile():Promise<string>;
